version: "3"
services:
  api:
    image: node:10
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "npm install && npm run dev"
    environment:
      #mailhog
      #MAIL_HOST: mailhog
      #MAIL_PORT: 1025
      #MAIL_DRIVER: smtp
      #app
      APP_PORT: ${APP_PORT}
      API_URL: ${APi_URL}
      #crypting
      PASSWORD_SALT: ${PASSWORD_SALT}
      #jwt
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      #db
      DB_URI: ${DB_URI}
      DB_NAME: ${DB_NAME}
      DB_AUTH_USERNAME: ${DB_AUTH_USERNAME}
      DB_AUTH_PASSWORD: ${DB_AUTH_PASSWORD}